In [1]:
from google.colab import files

uploaded_files = files.upload()

Saving RESOURCE.zip to RESOURCE.zip

In [2]:
import os

os.listdir("/content")

['.config', 'RESOURCE.zip', 'sample_data']

In [3]:
import os
import zipfile
from typing import List

import pandas as pd


def unzip_dataset(zip_path: str, extract_path: str) -> None:
    """
    Unzips the dataset to the given directory.
    """
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(extract_path)


def get_csv_files(folder_path: str) -> List[str]:
    """
    Returns all CSV file paths inside a folder.
    """
    csv_files = []

    for root, _, files in os.walk(folder_path):
        for file in files:
            if file.lower().endswith(".csv"):
                csv_files.append(os.path.join(root, file))

    if not csv_files:
        raise FileNotFoundError("No CSV files found")

    return csv_files


def read_csv_file_safe(file_path: str) -> pd.DataFrame:
    """
    Reads a CSV file with encoding fallback.
    """
    try:
        return pd.read_csv(file_path, encoding="utf-8")
    except UnicodeDecodeError:
        return pd.read_csv(file_path, encoding="latin1")


def read_csv_files(csv_files: List[str]) -> List[pd.DataFrame]:
    """
    Reads all CSV files safely.
    """
    dataframes = []

    for file in csv_files:
        df = read_csv_file_safe(file)
        dataframes.append(df)

    return dataframes


def merge_dataframes(dataframes: List[pd.DataFrame]) -> pd.DataFrame:
    """
    Merge multiple DataFrames into one.
    """
    return pd.concat(dataframes, ignore_index=True)


def save_dataframe(df: pd.DataFrame, output_path: str) -> None:
    """
    Save DataFrame to CSV.
    """
    df.to_csv(output_path, index=False)


def main() -> None:
    zip_file_path = "/content/RESOURCE.zip"
    extract_folder = "/content/extracted_data"
    output_file = "/content/merged_dataset.csv"

    unzip_dataset(zip_file_path, extract_folder)

    csv_files = get_csv_files(extract_folder)
    print(f"📂 CSV files found: {len(csv_files)}")

    dataframes = read_csv_files(csv_files)
    merged_df = merge_dataframes(dataframes)

    save_dataframe(merged_df, output_file)

    print("✅ Dataset merged successfully!")
    print(f"📄 Output file: {output_file}")
    print(f"📊 Final shape: {merged_df.shape}")


if __name__ == "__main__":
    main()

📂 CSV files found: 23
✅ Dataset merged successfully!
📄 Output file: /content/merged_dataset.csv
📊 Final shape: (195145, 25)

In [4]:
import pandas as pd
from IPython.display import display


def load_dataframe(file_path: str) -> pd.DataFrame:
    """
    Load CSV file into a pandas DataFrame.
    """
    return pd.read_csv(file_path)


def main() -> None:
    file_path = "/content/merged_dataset.csv"

    df = load_dataframe(file_path)

    print("✅ DataFrame created successfully")
    print(f"📊 Shape: {df.shape}")


    display(df.head(10))


if __name__ == "__main__":
    main()

✅ DataFrame created successfully
📊 Shape: (195145, 25)

,State Code,District Code,India/States,Division,Group,Class,NIC Name,Main Workers - Total - Persons,Main Workers - Total - Males,Main Workers - Total - Females,...,Main Workers - Urban - Females,Marginal Workers - Total - Persons,Marginal Workers - Total - Males,Marginal Workers - Total - Females,Marginal Workers - Rural - Persons,Marginal Workers - Rural - Males,Marginal Workers - Rural - Females,Marginal Workers - Urban - Persons,Marginal Workers - Urban - Males,Marginal Workers - Urban - Females
0,`14,`000,STATE - MANIPUR,`00,`000,`0000,Total,463655,311080,152575,...,73797,154250,57170,97080,96283,34860,61423,57967,22310,35657
1,`14,`000,STATE - MANIPUR,`01,`000,`0000,"Crop and animal production, hunting and relate...",12240,8443,3797,...,1490,5447,2804,2643,3968,2019,1949,1479,785,694
2,`14,`000,STATE - MANIPUR,`01,`011,`0000,Growing of non-perennial crops,6511,4268,2243,...,865,3610,1818,1792,2732,1374,1358,878,444,434
3,`14,`000,STATE - MANIPUR,`01,`011,`0111,"Growing of cereals (except rice), leguminous c...",27,21,6,...,1,30,8,22,28,8,20,2,0,2
4,`14,`000,STATE - MANIPUR,`01,`011,`0112,Growing of rice,5981,4028,1953,...,745,2915,1675,1240,2352,1285,1067,563,390,173
5,`14,`000,STATE - MANIPUR,`01,`011,`0113,"Growing of vegetables and melons, roots and tu...",484,200,284,...,119,655,129,526,342,75,267,313,54,259
6,`14,`000,STATE - MANIPUR,`01,`011,`0114,Growing of sugar cane,14,14,0,...,0,8,4,4,8,4,4,0,0,0
7,`14,`000,STATE - MANIPUR,`01,`011,`0119,Growing of other non-perennial crop,5,5,0,...,0,2,2,0,2,2,0,0,0,0
8,`14,`000,STATE - MANIPUR,`01,`012,`0000,Growing of perennial crops,649,356,293,...,19,130,81,49,112,65,47,18,16,2
9,`14,`000,STATE - MANIPUR,`01,`012,`0122,Growing of tropical and subtropical fruits,252,94,158,...,0,31,22,9,24,16,8,7,6,1

In [5]:
import pandas as pd
from IPython.display import display


def load_dataframe(file_path: str) -> pd.DataFrame:
    """
    Load merged CSV into DataFrame.
    """
    return pd.read_csv(file_path)


def basic_info(df: pd.DataFrame) -> None:
    """
    Display basic information about the dataset.
    """
    print("🔹 Dataset Shape (Rows, Columns):")
    print(df.shape)

    print("\n🔹 Column Names:")
    print(df.columns.tolist())

    print("\n🔹 Data Types:")
    print(df.dtypes)


def missing_value_analysis(df: pd.DataFrame) -> None:
    """
    Display missing value count per column.
    """
    missing_values = df.isnull().sum()
    result = missing_values[missing_values > 0]

    print("\n🔹 Missing Values Per Column:")
    if result.empty:
        print("✅ No missing values found.")
    else:
        print(result)


def statistical_summary(df: pd.DataFrame) -> None:
    """
    Display statistical summary for numerical columns.
    """
    print("\n🔹 Statistical Summary:")
    display(df.describe())




def data_quality_checks(df: pd.DataFrame) -> None:
    """
    Perform basic data quality checks.
    """
    print("\n🔹 DATA QUALITY ANALYSIS")


    duplicate_count = df.duplicated().sum()
    print(f"🔸 Duplicate records: {duplicate_count}")


    numeric_columns = df.select_dtypes(include="number").columns
    negative_values = (df[numeric_columns] < 0).sum().sum()
    print(f"🔸 Negative values found: {negative_values}")


    zero_values = (df[numeric_columns] == 0).sum()
    dominant_zero_columns = zero_values[zero_values > 0]

    print("\n🔸 Columns with zero values:")
    print(dominant_zero_columns.head())


    if (
        "Main Workers - Total - Persons" in df.columns
        and "Main Workers - Total - Males" in df.columns
        and "Main Workers - Total - Females" in df.columns
    ):
        inconsistent_rows = df[
            df["Main Workers - Total - Persons"]
            != df["Main Workers - Total - Males"]
            + df["Main Workers - Total - Females"]
        ]

        print(
            f"\n🔸 Inconsistent gender totals (Main Workers): "
            f"{len(inconsistent_rows)} rows"
        )


def sample_records(df: pd.DataFrame) -> None:
    """
    Display sample rows from dataset.
    """
    print("\n🔹 Sample Records:")
    display(df.head(10))


def main() -> None:
    file_path = "/content/merged_dataset.csv"

    df = load_dataframe(file_path)

    print("✅ Data Exploration Started")

    basic_info(df)
    missing_value_analysis(df)
    statistical_summary(df)
    data_quality_checks(df)
    sample_records(df)

    print("\n✅ Data Exploration Completed")


if __name__ == "__main__":
    main()

✅ Data Exploration Started
🔹 Dataset Shape (Rows, Columns):
(195145, 25)

🔹 Column Names:
['State Code', 'District Code', 'India/States', 'Division', 'Group', 'Class', 'NIC Name', 'Main Workers - Total -  Persons', 'Main Workers - Total - Males', 'Main Workers - Total - Females', 'Main Workers - Rural -  Persons', 'Main Workers - Rural - Males', 'Main Workers - Rural - Females', 'Main Workers - Urban -  Persons', 'Main Workers - Urban - Males', 'Main Workers - Urban - Females', 'Marginal Workers - Total -  Persons', 'Marginal Workers - Total - Males', 'Marginal Workers - Total - Females', 'Marginal Workers - Rural -  Persons', 'Marginal Workers - Rural - Males', 'Marginal Workers - Rural - Females', 'Marginal Workers - Urban -  Persons', 'Marginal Workers - Urban - Males', 'Marginal Workers - Urban - Females']

🔹 Data Types:
State Code                             object
District Code                          object
India/States                           object
Division                               object
Group                                  object
Class                                  object
NIC Name                               object
Main Workers - Total -  Persons         int64
Main Workers - Total - Males            int64
Main Workers - Total - Females          int64
Main Workers - Rural -  Persons         int64
Main Workers - Rural - Males            int64
Main Workers - Rural - Females          int64
Main Workers - Urban -  Persons         int64
Main Workers - Urban - Males            int64
Main Workers - Urban - Females          int64
Marginal Workers - Total -  Persons     int64
Marginal Workers - Total - Males        int64
Marginal Workers - Total - Females      int64
Marginal Workers - Rural -  Persons     int64
Marginal Workers - Rural - Males        int64
Marginal Workers - Rural - Females      int64
Marginal Workers - Urban -  Persons     int64
Marginal Workers - Urban - Males        int64
Marginal Workers - Urban - Females      int64
dtype: object

🔹 Missing Values Per Column:
✅ No missing values found.

🔹 Statistical Summary:

,Main Workers - Total - Persons,Main Workers - Total - Males,Main Workers - Total - Females,Main Workers - Rural - Persons,Main Workers - Rural - Males,Main Workers - Rural - Females,Main Workers - Urban - Persons,Main Workers - Urban - Males,Main Workers - Urban - Females,Marginal Workers - Total - Persons,Marginal Workers - Total - Males,Marginal Workers - Total - Females,Marginal Workers - Rural - Persons,Marginal Workers - Rural - Males,Marginal Workers - Rural - Females,Marginal Workers - Urban - Persons,Marginal Workers - Urban - Males,Marginal Workers - Urban - Females
count,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,1.951450e+05,195145.000000,195145.000000
mean,1.492138e+03,1.193171e+03,2.989664e+02,6.606187e+02,5.170353e+02,1.435834e+02,8.315188e+02,6.761358e+02,1.553830e+02,3.642672e+02,1.826322e+02,1.816350e+02,2.502286e+02,1.165241e+02,1.337045e+02,1.140386e+02,66.108094,47.930472
std,4.568169e+04,3.773917e+04,8.582019e+03,2.044436e+04,1.654295e+04,4.314446e+03,2.586781e+04,2.167339e+04,4.531593e+03,1.176940e+04,5.760575e+03,6.309699e+03,8.232274e+03,3.723078e+03,4.748460e+03,3.842889e+03,2132.581727,1803.271234
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,6.000000e+00,6.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
50%,2.800000e+01,2.300000e+01,3.000000e+00,1.200000e+01,8.000000e+00,0.000000e+00,1.200000e+01,9.000000e+00,0.000000e+00,4.000000e+00,2.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
75%,1.880000e+02,1.450000e+02,2.400000e+01,7.400000e+01,5.600000e+01,8.000000e+00,8.600000e+01,6.700000e+01,1.200000e+01,2.800000e+01,1.800000e+01,6.000000e+00,1.400000e+01,8.000000e+00,3.000000e+00,9.000000e+00,6.000000,2.000000
max,1.561976e+07,1.280140e+07,2.818356e+06,6.770444e+06,5.446541e+06,1.323903e+06,8.849315e+06,7.354862e+06,1.494453e+06,3.834122e+06,1.966750e+06,1.867372e+06,2.515182e+06,1.223824e+06,1.291358e+06,1.318940e+06,742926.000000,576014.000000

🔹 DATA QUALITY ANALYSIS
🔸 Duplicate records: 0
🔸 Negative values found: 0

🔸 Columns with zero values:
Main Workers - Total -  Persons     6862
Main Workers - Total - Males       13491
Main Workers - Total - Females     75770
Main Workers - Rural -  Persons    40562
Main Workers - Rural - Males       46976
dtype: int64

🔹 Sample Records:

,State Code,District Code,India/States,Division,Group,Class,NIC Name,Main Workers - Total - Persons,Main Workers - Total - Males,Main Workers - Total - Females,...,Main Workers - Urban - Females,Marginal Workers - Total - Persons,Marginal Workers - Total - Males,Marginal Workers - Total - Females,Marginal Workers - Rural - Persons,Marginal Workers - Rural - Males,Marginal Workers - Rural - Females,Marginal Workers - Urban - Persons,Marginal Workers - Urban - Males,Marginal Workers - Urban - Females
0,`14,`000,STATE - MANIPUR,`00,`000,`0000,Total,463655,311080,152575,...,73797,154250,57170,97080,96283,34860,61423,57967,22310,35657
1,`14,`000,STATE - MANIPUR,`01,`000,`0000,"Crop and animal production, hunting and relate...",12240,8443,3797,...,1490,5447,2804,2643,3968,2019,1949,1479,785,694
2,`14,`000,STATE - MANIPUR,`01,`011,`0000,Growing of non-perennial crops,6511,4268,2243,...,865,3610,1818,1792,2732,1374,1358,878,444,434
3,`14,`000,STATE - MANIPUR,`01,`011,`0111,"Growing of cereals (except rice), leguminous c...",27,21,6,...,1,30,8,22,28,8,20,2,0,2
4,`14,`000,STATE - MANIPUR,`01,`011,`0112,Growing of rice,5981,4028,1953,...,745,2915,1675,1240,2352,1285,1067,563,390,173
5,`14,`000,STATE - MANIPUR,`01,`011,`0113,"Growing of vegetables and melons, roots and tu...",484,200,284,...,119,655,129,526,342,75,267,313,54,259
6,`14,`000,STATE - MANIPUR,`01,`011,`0114,Growing of sugar cane,14,14,0,...,0,8,4,4,8,4,4,0,0,0
7,`14,`000,STATE - MANIPUR,`01,`011,`0119,Growing of other non-perennial crop,5,5,0,...,0,2,2,0,2,2,0,0,0,0
8,`14,`000,STATE - MANIPUR,`01,`012,`0000,Growing of perennial crops,649,356,293,...,19,130,81,49,112,65,47,18,16,2
9,`14,`000,STATE - MANIPUR,`01,`012,`0122,Growing of tropical and subtropical fruits,252,94,158,...,0,31,22,9,24,16,8,7,6,1

✅ Data Exploration Completed

In [14]:
import pandas as pd



def load_dataframe(file_path: str) -> pd.DataFrame:
    """
    Load CSV file into DataFrame.
    """
    return pd.read_csv(file_path)


def clean_column_names(df: pd.DataFrame) -> pd.DataFrame:
    """
    Standardize column names to snake_case.
    """
    df.columns = (
        df.columns.str.strip()
        .str.lower()
        .str.replace(r"[^\w\s]", " ", regex=True)
        .str.replace(r"\s+", "_", regex=True)
    )
    return df


def clean_string_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Remove unwanted characters from string columns.
    """
    string_columns = df.select_dtypes(include="object").columns

    for col in string_columns:
        df[col] = (
            df[col]
            .astype(str)
            .str.replace("`", "", regex=False)
            .str.strip()
        )

    return df


def create_nlp_text_column(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create a cleaned text column for NLP from industry name.
    """
    df["industry_text"] = (
        df["nic_name"]
        .str.lower()
        .str.replace(r"[^a-z\s]", "", regex=True)
        .str.replace(r"\s+", " ", regex=True)
        .str.strip()
    )

    return df


def data_cleaning_pipeline(df: pd.DataFrame) -> pd.DataFrame:
    """
    Complete data cleaning pipeline.
    """
    df = clean_column_names(df)
    df = clean_string_columns(df)
    df = create_nlp_text_column(df)
    return df


def save_cleaned_data(df: pd.DataFrame, output_path: str) -> None:
    """
    Save cleaned DataFrame.
    """
    df.to_csv(output_path, index=False)


def main() -> None:
    input_file = "/content/merged_dataset.csv"
    output_file = "/content/cleaned_dataset.csv"

    df = load_dataframe(input_file)
    cleaned_df = data_cleaning_pipeline(df)
    save_cleaned_data(cleaned_df, output_file)

    print("✅ Data Cleaning Completed Successfully")
    print(f"📄 Cleaned dataset saved at: {output_file}")
    print(f"📊 Shape after cleaning: {cleaned_df.shape}")
    print("\n🔍 Cleaned Columns:")
    print(cleaned_df.columns.tolist())


if __name__ == "__main__":
    main()

✅ Data Cleaning Completed Successfully
📄 Cleaned dataset saved at: /content/cleaned_dataset.csv
📊 Shape after cleaning: (195145, 26)

🔍 Cleaned Columns:
['state_code', 'district_code', 'india_states', 'division', 'group', 'class', 'nic_name', 'main_workers_total_persons', 'main_workers_total_males', 'main_workers_total_females', 'main_workers_rural_persons', 'main_workers_rural_males', 'main_workers_rural_females', 'main_workers_urban_persons', 'main_workers_urban_males', 'main_workers_urban_females', 'marginal_workers_total_persons', 'marginal_workers_total_males', 'marginal_workers_total_females', 'marginal_workers_rural_persons', 'marginal_workers_rural_males', 'marginal_workers_rural_females', 'marginal_workers_urban_persons', 'marginal_workers_urban_males', 'marginal_workers_urban_females', 'industry_text']

In [7]:
from IPython.display import display
import pandas as pd

df = pd.read_csv("/content/cleaned_dataset.csv")
display(df.head(10))

,state_code,district_code,india_states,division,group,class,nic_name,main_workers_total_persons,main_workers_total_males,main_workers_total_females,...,marginal_workers_total_persons,marginal_workers_total_males,marginal_workers_total_females,marginal_workers_rural_persons,marginal_workers_rural_males,marginal_workers_rural_females,marginal_workers_urban_persons,marginal_workers_urban_males,marginal_workers_urban_females,industry_text
0,14,0,STATE - MANIPUR,0,0,0,Total,463655,311080,152575,...,154250,57170,97080,96283,34860,61423,57967,22310,35657,total
1,14,0,STATE - MANIPUR,1,0,0,"Crop and animal production, hunting and relate...",12240,8443,3797,...,5447,2804,2643,3968,2019,1949,1479,785,694,crop and animal production hunting and related...
2,14,0,STATE - MANIPUR,1,11,0,Growing of non-perennial crops,6511,4268,2243,...,3610,1818,1792,2732,1374,1358,878,444,434,growing of nonperennial crops
3,14,0,STATE - MANIPUR,1,11,111,"Growing of cereals (except rice), leguminous c...",27,21,6,...,30,8,22,28,8,20,2,0,2,growing of cereals except rice leguminous crop...
4,14,0,STATE - MANIPUR,1,11,112,Growing of rice,5981,4028,1953,...,2915,1675,1240,2352,1285,1067,563,390,173,growing of rice
5,14,0,STATE - MANIPUR,1,11,113,"Growing of vegetables and melons, roots and tu...",484,200,284,...,655,129,526,342,75,267,313,54,259,growing of vegetables and melons roots and tubers
6,14,0,STATE - MANIPUR,1,11,114,Growing of sugar cane,14,14,0,...,8,4,4,8,4,4,0,0,0,growing of sugar cane
7,14,0,STATE - MANIPUR,1,11,119,Growing of other non-perennial crop,5,5,0,...,2,2,0,2,2,0,0,0,0,growing of other nonperennial crop
8,14,0,STATE - MANIPUR,1,12,0,Growing of perennial crops,649,356,293,...,130,81,49,112,65,47,18,16,2,growing of perennial crops
9,14,0,STATE - MANIPUR,1,12,122,Growing of tropical and subtropical fruits,252,94,158,...,31,22,9,24,16,8,7,6,1,growing of tropical and subtropical fruits

In [8]:
import pandas as pd


def load_cleaned_data(file_path: str) -> pd.DataFrame:
    """
    Load cleaned dataset.
    """
    return pd.read_csv(file_path)


def create_worker_totals(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create total worker-related features.
    """
    df["total_workers"] = (
        df["main_workers_total_persons"]
        + df["marginal_workers_total_persons"]
    )

    df["total_male_workers"] = (
        df["main_workers_total_males"]
        + df["marginal_workers_total_males"]
    )

    df["total_female_workers"] = (
        df["main_workers_total_females"]
        + df["marginal_workers_total_females"]
    )

    return df


def create_area_based_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create rural and urban worker totals.
    """
    df["total_rural_workers"] = (
        df["main_workers_rural_persons"]
        + df["marginal_workers_rural_persons"]
    )

    df["total_urban_workers"] = (
        df["main_workers_urban_persons"]
        + df["marginal_workers_urban_persons"]
    )

    return df


def create_worker_type_feature(df: pd.DataFrame) -> pd.DataFrame:
    """
    Identify dominant worker type.
    """
    df["dominant_worker_type"] = df.apply(
        lambda row: "Main"
        if row["main_workers_total_persons"]
        >= row["marginal_workers_total_persons"]
        else "Marginal",
        axis=1
    )

    return df


def create_nlp_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create NLP-related features.
    """
    df["industry_word_count"] = df["industry_text"].apply(
        lambda x: len(str(x).split())
    )

    return df


def feature_engineering_pipeline(df: pd.DataFrame) -> pd.DataFrame:
    """
    Complete feature engineering pipeline.
    """
    df = create_worker_totals(df)
    df = create_area_based_features(df)
    df = create_worker_type_feature(df)
    df = create_nlp_features(df)

    return df


def save_feature_engineered_data(df: pd.DataFrame, output_path: str) -> None:
    """
    Save feature engineered dataset.
    """
    df.to_csv(output_path, index=False)


def main() -> None:
    input_file = "/content/cleaned_dataset.csv"
    output_file = "/content/feature_engineered_dataset.csv"

    df = load_cleaned_data(input_file)
    fe_df = feature_engineering_pipeline(df)

    save_feature_engineered_data(fe_df, output_file)

    print("✅ Feature Engineering Completed")
    print(f"📄 Saved at: {output_file}")
    print(f"📊 Final shape: {fe_df.shape}")
    print("\n🔍 New Features Added:")
    print(
        [
            "total_workers",
            "total_male_workers",
            "total_female_workers",
            "total_rural_workers",
            "total_urban_workers",
            "dominant_worker_type",
            "industry_word_count",
        ]
    )


if __name__ == "__main__":
    main()

✅ Feature Engineering Completed
📄 Saved at: /content/feature_engineered_dataset.csv
📊 Final shape: (195145, 33)

🔍 New Features Added:
['total_workers', 'total_male_workers', 'total_female_workers', 'total_rural_workers', 'total_urban_workers', 'dominant_worker_type', 'industry_word_count']

In [9]:
from IPython.display import display
import pandas as pd

df = pd.read_csv("/content/feature_engineered_dataset.csv")
display(df.head(10))

,state_code,district_code,india_states,division,group,class,nic_name,main_workers_total_persons,main_workers_total_males,main_workers_total_females,...,marginal_workers_urban_males,marginal_workers_urban_females,industry_text,total_workers,total_male_workers,total_female_workers,total_rural_workers,total_urban_workers,dominant_worker_type,industry_word_count
0,14,0,STATE - MANIPUR,0,0,0,Total,463655,311080,152575,...,22310,35657,total,617905,368250,249655,346927,270978,Main,1
1,14,0,STATE - MANIPUR,1,0,0,"Crop and animal production, hunting and relate...",12240,8443,3797,...,785,694,crop and animal production hunting and related...,17687,11247,6440,10967,6720,Main,9
2,14,0,STATE - MANIPUR,1,11,0,Growing of non-perennial crops,6511,4268,2243,...,444,434,growing of nonperennial crops,10121,6086,4035,6456,3665,Main,4
3,14,0,STATE - MANIPUR,1,11,111,"Growing of cereals (except rice), leguminous c...",27,21,6,...,0,2,growing of cereals except rice leguminous crop...,57,29,28,54,3,Marginal,10
4,14,0,STATE - MANIPUR,1,11,112,Growing of rice,5981,4028,1953,...,390,173,growing of rice,8896,5703,3193,5767,3129,Main,3
5,14,0,STATE - MANIPUR,1,11,113,"Growing of vegetables and melons, roots and tu...",484,200,284,...,54,259,growing of vegetables and melons roots and tubers,1139,329,810,616,523,Marginal,8
6,14,0,STATE - MANIPUR,1,11,114,Growing of sugar cane,14,14,0,...,0,0,growing of sugar cane,22,18,4,16,6,Main,4
7,14,0,STATE - MANIPUR,1,11,119,Growing of other non-perennial crop,5,5,0,...,0,0,growing of other nonperennial crop,7,7,0,3,4,Main,5
8,14,0,STATE - MANIPUR,1,12,0,Growing of perennial crops,649,356,293,...,16,2,growing of perennial crops,779,437,342,669,110,Main,4
9,14,0,STATE - MANIPUR,1,12,122,Growing of tropical and subtropical fruits,252,94,158,...,6,1,growing of tropical and subtropical fruits,283,116,167,270,13,Main,6

In [10]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split


def load_feature_engineered_data(file_path: str) -> pd.DataFrame:
    """
    Load feature engineered dataset.
    """
    return pd.read_csv(file_path)


def create_business_category(industry_text: str) -> str:
    """
    Rule-based NLP mapping for business category.
    """
    text = str(industry_text).lower()

    if any(word in text for word in ["retail", "shop", "trade"]):
        return "Retail"
    if any(word in text for word in ["poultry", "chicken", "livestock"]):
        return "Poultry"
    if any(word in text for word in ["agriculture", "crop", "farming", "cultivation"]):
        return "Agriculture"
    if any(word in text for word in ["manufacture", "factory", "production"]):
        return "Manufacturing"
    if any(word in text for word in ["construction", "building", "infrastructure"]):
        return "Construction"

    return "Others"


def prepare_target_variable(df: pd.DataFrame) -> pd.DataFrame:
    """
    Create target variable for model.
    """
    df["business_category"] = df["industry_text"].apply(
        create_business_category
    )
    return df


def split_data(df: pd.DataFrame):
    """
    Split dataset into train and test sets.
    """
    x = df["industry_text"]
    y = df["business_category"]

    return train_test_split(
        x, y, test_size=0.2, random_state=42, stratify=y
    )


def train_model(x_train, y_train):
    """
    Train TF-IDF + Logistic Regression model.
    """
    vectorizer = TfidfVectorizer(stop_words="english", max_features=5000)
    x_train_tfidf = vectorizer.fit_transform(x_train)

    model = LogisticRegression(max_iter=1000)
    model.fit(x_train_tfidf, y_train)

    return model, vectorizer


def evaluate_model(model, vectorizer, x_test, y_test) -> None:
    """
    Evaluate trained model.
    """
    x_test_tfidf = vectorizer.transform(x_test)
    predictions = model.predict(x_test_tfidf)

    accuracy = accuracy_score(y_test, predictions)

    print("✅ MODEL EVALUATION RESULTS")
    print(f"🎯 Accuracy: {accuracy:.2f}")
    print("\n📊 Classification Report:")
    print(classification_report(y_test, predictions))


def main() -> None:
    file_path = "/content/feature_engineered_dataset.csv"

    df = load_feature_engineered_data(file_path)
    df = prepare_target_variable(df)

    x_train, x_test, y_train, y_test = split_data(df)

    model, vectorizer = train_model(x_train, y_train)

    evaluate_model(model, vectorizer, x_test, y_test)


if __name__ == "__main__":
    main()

✅ MODEL EVALUATION RESULTS
🎯 Accuracy: 1.00

📊 Classification Report:
               precision    recall  f1-score   support

  Agriculture       1.00      1.00      1.00       772
 Construction       1.00      1.00      1.00      1611
Manufacturing       1.00      1.00      1.00      9479
       Others       1.00      1.00      1.00     24263
      Poultry       1.00      1.00      1.00        67
       Retail       1.00      1.00      1.00      2837

     accuracy                           1.00     39029
    macro avg       1.00      1.00      1.00     39029
 weighted avg       1.00      1.00      1.00     39029

In [11]:
import pandas as pd

df = pd.read_csv("/content/feature_engineered_dataset.csv")


def create_business_category(industry_text: str) -> str:
    text = str(industry_text).lower()
    if any(word in text for word in ["retail", "shop", "trade"]):
        return "Retail"
    if any(word in text for word in ["poultry", "chicken", "livestock"]):
        return "Poultry"
    if any(word in text for word in ["agriculture", "crop", "farming", "cultivation"]):
        return "Agriculture"
    if any(word in text for word in ["manufacture", "factory", "production"]):
        return "Manufacturing"
    if any(word in text for word in ["construction", "building", "infrastructure"]):
        return "Construction"
    return "Others"

df["business_category"] = df["industry_text"].apply(create_business_category)


print(df["business_category"].value_counts())

business_category
Others           121314
Manufacturing     47398
Retail            14183
Construction       8058
Agriculture        3859
Poultry             333
Name: count, dtype: int64

In [12]:
!pip install streamlit plotly

Collecting streamlit
  Downloading streamlit-1.54.0-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Collecting cachetools<7,>=5.5 (from streamlit)
  Downloading cachetools-6.2.6-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.1.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.54.0-py3-none-any.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 92.7 MB/s eta 0:00:00
Downloading cachetools-6.2.6-py3-none-any.whl (11 kB)
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 89.1 MB/s eta 0:00:00
Installing collected packages: cachetools, pydeck, streamlit
  Attempting uninstall: cachetools
    Found existing installation: cachetools 7.0.1
    Uninstalling cachetools-7.0.1:
      Successfully uninstalled cachetools-7.0.1
Successfully installed cachetools-6.2.6 pydeck-0.9.1 streamlit-1.54.0

In [18]:
%%writefile app.py
import pandas as pd
import plotly.express as px
import streamlit as st


@st.cache_data
def load_data() -> pd.DataFrame:
    """
    Load feature engineered dataset.
    """
    return pd.read_csv("feature_engineered_dataset.csv")


def business_category_mapping(industry_text: str) -> str:
    """
    Rule-based NLP mapping to business categories.
    """
    text = str(industry_text).lower()

    if any(word in text for word in ["retail", "trade", "shop"]):
        return "Retail"
    if any(word in text for word in ["poultry", "chicken"]):
        return "Poultry"
    if any(word in text for word in ["agriculture", "crop", "farming"]):
        return "Agriculture"
    if any(word in text for word in ["manufacture", "production", "factory"]):
        return "Manufacturing"
    if any(word in text for word in ["construction", "building"]):
        return "Construction"

    return "Others"


def prepare_dashboard_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Prepare business category column.
    """

    df = df[df["india_states"].str.startswith("STATE")].copy()

    df["business_category"] = df["industry_text"].apply(
        business_category_mapping
    )
    return df




def plot_workers_by_category(df: pd.DataFrame) -> None:
    """
    Bar chart: Total workers by business category.
    """

    grouped = df.groupby("business_category")["total_workers"].sum().reset_index()

    fig = px.bar(
        grouped,
        x="business_category",
        y="total_workers",
        title="Total Workers by Business Category"
    )
    st.plotly_chart(fig, width="stretch")


def plot_workers_by_state(df: pd.DataFrame) -> None:
    """
    Bar chart: Top 10 states by worker population.
    """


    grouped = (
        df.groupby("india_states")["total_workers"]
        .sum()
        .reset_index()
        .sort_values("total_workers", ascending=False)
        .head(10)
    )

    fig = px.bar(
        grouped,
        x="india_states",
        y="total_workers",
        title="Top 10 States by Worker Population"
    )
    st.plotly_chart(fig, width="stretch")




def plot_rural_urban_split(df: pd.DataFrame) -> None:
    """
    Pie chart: Rural vs Urban worker distribution.
    """

    data = pd.DataFrame({
        "Area": ["Rural", "Urban"],
        "Workers": [
            df["total_rural_workers"].sum(),
            df["total_urban_workers"].sum()
        ]
    })

    fig = px.pie(
        data,
        names="Area",
        values="Workers",
        title="Rural vs Urban Worker Distribution"
    )
    st.plotly_chart(fig, width="stretch")


def plot_gender_distribution(df: pd.DataFrame) -> None:
    """
    Bar chart: Male vs Female worker distribution.
    """

    data = pd.DataFrame({
        "Gender": ["Male", "Female"],
        "Workers": [
            df["total_male_workers"].sum(),
            df["total_female_workers"].sum()
        ]
    })

    fig = px.bar(
        data,
        x="Gender",
        y="Workers",
        title="Gender-wise Worker Distribution"
    )
    st.plotly_chart(fig, width="stretch")


def plot_female_participation_by_industry(df: pd.DataFrame) -> None:
    """
    Bar chart: Female workforce by business category.
    """

    grouped = (
        df.groupby("business_category")["total_female_workers"]
        .sum()
        .reset_index()
    )

    fig = px.bar(
        grouped,
        x="business_category",
        y="total_female_workers",
        title="Female Workforce by Industry"
    )
    st.plotly_chart(fig, width="stretch")


def display_facts(df: pd.DataFrame) -> None:
    """
    Display key facts and figures about the workforce.
    """

    st.subheader("📌 Key Facts & Figures")

    st.write(f"• **Total Workforce:** {int(df['total_workers'].sum()):,}")
    st.write(
        f"• **Dominant Industry:** "
        f"{df.groupby('business_category')['total_workers'].sum().drop('Others').idxmax()}"
    )
    st.write(
        f"• **Highest Employment State:** "
        f"{df.groupby('india_states')['total_workers'].sum().idxmax()}"
    )
    st.write(
        f"• **Total Rural Workers:** {int(df['total_rural_workers'].sum()):,}"
    )
    st.write(
        f"• **Total Urban Workers:** {int(df['total_urban_workers'].sum()):,}"
    )



def main() -> None:
    st.set_page_config(
        page_title="Industrial Workforce Dashboard",
        layout="wide"
    )

    st.title("📊 Industrial Human Resource Geo-Visualization")

    df = load_data()
    df = prepare_dashboard_data(df)

    section = st.selectbox(
        "Select Analysis View",
        (
            "Industry-wise Analysis",
            "Geography-wise Analysis",
            "Rural vs Urban Distribution",
            "Gender Analysis",
            "Key Facts & Insights"
        )
    )

    if section == "Industry-wise Analysis":
        plot_workers_by_category(df)
        plot_female_participation_by_industry(df)

    elif section == "Geography-wise Analysis":
        plot_workers_by_state(df)


    elif section == "Rural vs Urban Distribution":
        plot_rural_urban_split(df)

    elif section == "Gender Analysis":
        plot_gender_distribution(df)

    elif section == "Key Facts & Insights":
        display_facts(df)


if __name__ == "__main__":
    main()

Overwriting app.py

In [19]:
# --- Colab Streamlit + Cloudflared Setup ---

# 1️⃣ Install dependencies
!pip install streamlit pandas requests --quiet

# 2️⃣ Download and install cloudflared
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

# 3️⃣ Kill any old processes
!pkill -f streamlit
!pkill -f cloudflared

# 4️⃣ Run Streamlit app in background and log output
!nohup streamlit run app.py --server.port 8501 --server.headless true > log.txt 2>&1 &

import time
print("⏳ Waiting 10 seconds for Streamlit to start...")
time.sleep(10)

# 5️⃣ Check if Streamlit is running
!tail -n 20 log.txt

# 6️⃣ Start Cloudflared tunnel (after Streamlit is up)
!cloudflared tunnel --url http://localhost:8501 --no-autoupdate

(Reading database ... 117544 files and directories currently installed.)
Preparing to unpack cloudflared-linux-amd64.deb ...
Unpacking cloudflared (2026.2.0) over (2026.2.0) ...
Setting up cloudflared (2026.2.0) ...
Processing triggers for man-db (2.10.2-1) ...
⏳ Waiting 10 seconds for Streamlit to start...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.86.126.166:8501

2026-02-19T08:04:36Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-02-19T08:04:36Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-02-19T08:04:39Z INF +--------------------------------------------------------------------------------------------+
2026-02-19T08:04:39Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-02-19T08:04:39Z INF |  https://pharmacology-action-vote-impose.trycloudflare.com                                 |
2026-02-19T08:04:39Z INF +--------------------------------------------------------------------------------------------+
2026-02-19T08:04:39Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-02-19T08:04:39Z INF Version 2026.2.0 (Checksum 176746db3be7dc7bd48f3dd287c8930a4645ebb6e6700f883fddda5a4c307c16)
2026-02-19T08:04:39Z INF GOOS: linux, GOVersion: go1.24.13, GoArch: amd64
2026-02-19T08:04:39Z INF Settings: map[ha-connections:1 no-autoupdate:true protocol:quic url:http://localhost:8501]
2026-02-19T08:04:39Z INF cloudflared will not automatically update if installed by a package manager.
2026-02-19T08:04:39Z INF Generated Connector ID: aad935db-24e6-4383-bdf5-e71fd6993218
2026-02-19T08:04:39Z INF Initial protocol quic
2026-02-19T08:04:39Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-02-19T08:04:39Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-02-19T08:04:39Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-02-19T08:04:39Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-02-19T08:04:39Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-02-19T08:04:39Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveP256] connIndex=0 event=0 ip=198.41.200.33
2026/02/19 08:04:39 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-02-19T08:04:39Z INF Registered tunnel connection connIndex=0 connection=ffe71aba-d56f-49d1-8d22-81a9fa9d1e85 event=0 ip=198.41.200.33 location=iad08 protocol=quic
2026-02-19T08:07:33Z INF Initiating graceful shutdown due to signal interrupt ...
^C